### PR TITLE
Update link to zend-router

### PR DESCRIPTION
**Pull request by Koopzington**

### CODE REVIEW

**Comment by michaelmoussa** [comment]
Thanks!

**Comment by xtreamwayz** [comment]
@michaelmoussa shouldn't this be merged into develop as well?

**Comment by michaelmoussa** [comment]
Whoops, good catch. Thanks @xtreamwayz

**Comment by xtreamwayz** [comment]
No, thanks to @Koopzington, he told me on IRC.

**Comment by Koopzington** [comment]
oh stop it, you... 😊

**Pull request merged**
